### ISSUE TITLE
Some possible bugs

### ISSUE THREAD

**Issue by net4u** [JHNBOS/MVC-Invoice#2]
When I try to delete some entries (e.g. Products, Invoices etc.) is entering in a loop like mode: nothing happens, but also no exception is fired. Also any kind of rendered HTML on page disappear.

**Comment by JHNBOS** [comment]
Hey, I want to thank you for noticing these bugs, and for the recommendations. I will try to fix the bugs and try to implement the recommendations.

**Comment by net4u** [comment]
I added a breakpoint here in InvoiceController.cs
private async Task DeleteInvoice(int id)
at:
            Invoice invoice = await GetInvoice(id);
but is never reached in VS2017

**Comment by JHNBOS** [comment]
I have tried it myself, and when I run it, the delete functions for debtors, products and invoices work. I did change some settings for the database. Maybe it helps now.

**Comment by net4u** [comment]
OK, I will try again and then comeback with comments if necessary

**Comment by net4u** [comment]
I can't succeed. Don't know what happens.

**Comment by JHNBOS** [comment]
Sorry, apparently one of the fixes didn't stay. Hopefully it will work now.

**Comment by net4u** [comment]
You broke a little in UserController as follows (you added in AppSettings model the properties I suggest, but you keep UserController as it was):

                _settings.CompanyNumber = AppSettings.CompanyNumber; //here you changed in AppSettings model to RegNumber
                _settings.CommerceNumber = AppSettings.CommerceNumber; //here you changed in AppSettings to FinnancialNumber

Anyway I will search to find if are more to correct.

**Comment by JHNBOS** [comment]
Yes, I am replacing this now according to your model. I still have to upload the new version

**Comment by net4u** [comment]
Maybe is better to keep your name conventions, to broke nothing. Is better because you are familiar with it.  In fact is only one property that comes supplementary, let's name it eg. VIESCompanyNumber (or whatever). I don't know how is naming in Nederland, here in Romania financial number (VAT related) is Company Number, and registration number is Commerce Number.

**Comment by net4u** [comment]
Anyway, sorry to bother you, but it seems to me that you are not in a final stage, and it may be better to change some little aspects now. I mean in terms of usability.
I may think at some properties to add as already mentioned above (BankName, VIESCommerceNumber), and maybe you can consider a kind of simple multi-tenat approach by this way: you recommend to create a first (and then subsequent) user by entering /Admin . OK, next when you login as admin (let say tenant) filter the available invoices and debtors by the (Legal)Name of given admin user: let say we have users admin@company1.name, admin@company2.name etc. each of them belongs to Company1, Company2 and so on. In this way the data is "filtered" by CompanyName as follows. 
In what concerns Debtors I have nothing to comment about being also in Users table, but keep also this consideration in mind.

**Comment by net4u** [comment]
And of course don't forget to reflect all this in DB migrations.
